import {
  Beneficiary,
  Volunteer,
  AssistanceRequest,
  Delivery,
  EmergencyAlert,
  MarketProduct,
  MarketOrder,
  ActivityLog,
  FoodRecord,
} from '../types';

export const INITIAL_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'ben-001',
    code: 'CN-KUM-001',
    name: 'Lakshmi Devi',
    age: 72,
    gender: 'Female',
    area: 'Kumbakonam Town',
    address: '14/B Melacauvery Street, Near Mahamaham Tank, Kumbakonam',
    phone: '+91 94432 10871',
    emergencyContact: '+91 98421 55601',
    emergencyContactRelation: 'Daughter (Revathi)',
    foodRequirement: 'Ponni Boiled Rice, Toor Dal, Fresh Veggies',
    currentStockKg: 0.5,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'critical',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 29.2,
    ambientHumidity: 62,
    coords: { lat: 10.9625, lng: 79.3831 },
    locationSharingActive: true,
    locationLastUpdated: '10 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Low sodium diet, soft cooked vegetables, vegetarian',
    healthNotes: 'Mild arthritis, relies on walking stick',
    registeredDate: '12 Jan 2026',
    assistanceHistory: [
      {
        id: 'hist-1',
        date: '2026-09-20',
        type: 'Rice & Provisions Kit',
        status: 'Delivered',
        notes: 'Delivered 3kg rice by Volunteer Arun Kumar',
      },
      {
        id: 'hist-2',
        date: '2026-09-12',
        type: 'Cooked Lunch Assistance',
        status: 'Delivered',
        notes: 'Special festival sambar sadham delivered',
      },
    ],
  },
  {
    id: 'ben-002',
    code: 'CN-KUM-002',
    name: 'Ramasamy',
    age: 76,
    gender: 'Male',
    area: 'Darasuram',
    address: '42 Sannathi Street, Opp. Airavatesvara Temple, Darasuram',
    phone: '+91 94431 87290',
    emergencyContact: '+91 97892 41102',
    emergencyContactRelation: 'Neighbour (Karthik)',
    foodRequirement: 'Raw Rice, Moong Dal, Gingelly Oil',
    currentStockKg: 0.8,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'critical',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 30.1,
    ambientHumidity: 59,
    coords: { lat: 10.9582, lng: 79.3564 },
    locationSharingActive: true,
    locationLastUpdated: '25 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Diabetic care, needs warm kanji twice a day',
    healthNotes: 'Hypertension, mobility restricted',
    registeredDate: '03 Feb 2026',
    assistanceHistory: [
      {
        id: 'hist-3',
        date: '2026-09-18',
        type: 'Dry Ration Kit',
        status: 'Delivered',
        notes: 'Handed over to neighbor with receipt',
      },
    ],
  },
  {
    id: 'ben-003',
    code: 'CN-KUM-003',
    name: 'Meenakshi',
    age: 74,
    gender: 'Female',
    area: 'Swamimalai',
    address: '8 West Car Street, Near Murugan Temple Steps, Swamimalai',
    phone: '+91 94420 33819',
    emergencyContact: '+91 93601 77291',
    emergencyContactRelation: 'Son in Chennai (Anand)',
    foodRequirement: 'Millet Flakes, Steamed Rice, Green Gram',
    currentStockKg: 2.8,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'sufficient',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'completed',
      dinner: 'pending',
    },
    ambientTemp: 28.6,
    ambientHumidity: 65,
    coords: { lat: 10.9568, lng: 79.3289 },
    locationSharingActive: true,
    locationLastUpdated: '1 hour ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Prefers ragi and traditional thina kanji',
    healthNotes: 'Active, can prepare light meals if provisions exist',
    registeredDate: '15 Feb 2026',
    assistanceHistory: [
      {
        id: 'hist-4',
        date: '2026-09-22',
        type: 'Millet Provision Box',
        status: 'Delivered',
        notes: 'Sufficient supplies for 10 days',
      },
    ],
  },
  {
    id: 'ben-004',
    code: 'CN-KUM-004',
    name: 'Gopal',
    age: 81,
    gender: 'Male',
    area: 'Patteeswaram',
    address: '27 Durgai Amman Kovil South Mada Veethi, Patteeswaram',
    phone: '+91 94862 11903',
    emergencyContact: '+91 94438 99014',
    emergencyContactRelation: 'Caretaker (Venkatesh)',
    foodRequirement: 'Soft Boiled Rice, Rasam Mix, Milk Powder',
    currentStockKg: 0.6,
    requiredStockKg: 2.5,
    stockUnit: 'kg',
    foodStatus: 'critical',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 29.8,
    ambientHumidity: 60,
    coords: { lat: 10.9241, lng: 79.3621 },
    locationSharingActive: true,
    locationLastUpdated: '15 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Pure liquid/semi-solid texture food only',
    healthNotes: 'Bedridden stage, requires daily check-ins',
    registeredDate: '28 Jan 2026',
    assistanceHistory: [
      {
        id: 'hist-5',
        date: '2026-09-19',
        type: 'Elderly Nutrition Pouch',
        status: 'Delivered',
        notes: 'Delivered by Volunteer Deepa Balan',
      },
    ],
  },
  {
    id: 'ben-005',
    code: 'CN-KUM-005',
    name: 'Saraswathi',
    age: 70,
    gender: 'Female',
    area: 'Nachiyarkoil',
    address: '5 Brass Artisan Lane, Near Srinivasa Perumal Kovil, Nachiyarkoil',
    phone: '+91 94435 77102',
    emergencyContact: '+91 98432 00192',
    emergencyContactRelation: 'Sister (Kalyani)',
    foodRequirement: 'Rice, Sambar Vegetables, Tamarind',
    currentStockKg: 1.1,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'low',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 29.5,
    ambientHumidity: 63,
    coords: { lat: 10.9163, lng: 79.4452 },
    locationSharingActive: true,
    locationLastUpdated: '40 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Vegetarian, standard South Indian meals',
    healthNotes: 'Mild cataracts in right eye',
    registeredDate: '05 Mar 2026',
    assistanceHistory: [
      {
        id: 'hist-6',
        date: '2026-09-16',
        type: 'Weekly Provisions',
        status: 'Delivered',
        notes: 'Delivered with vegetable box',
      },
    ],
  },
  {
    id: 'ben-006',
    code: 'CN-KUM-006',
    name: 'Murugan',
    age: 78,
    gender: 'Male',
    area: 'Thiruvidaimarudur',
    address: '19 Mahalingaswamy North Street, Thiruvidaimarudur',
    phone: '+91 94437 66291',
    emergencyContact: '+91 97910 88201',
    emergencyContactRelation: 'Nephew (Senthil)',
    foodRequirement: 'Idli Rice, Urad Dal, Ghee',
    currentStockKg: 2.5,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'sufficient',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'completed',
      dinner: 'pending',
    },
    ambientTemp: 29.0,
    ambientHumidity: 66,
    coords: { lat: 10.9992, lng: 79.4589 },
    locationSharingActive: true,
    locationLastUpdated: '3 hours ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Regular diet, no allergies',
    healthNotes: 'Healthy, good hearing and vision',
    registeredDate: '10 Feb 2026',
    assistanceHistory: [
      {
        id: 'hist-7',
        date: '2026-09-21',
        type: 'Monthly Kit',
        status: 'Delivered',
        notes: 'Received with signature',
      },
    ],
  },
  {
    id: 'ben-007',
    code: 'CN-KUM-007',
    name: 'Kamala Devi',
    age: 79,
    gender: 'Female',
    area: 'Kumbakonam Town',
    address: '88 Big Bazaar Street, Old Bus Stand Backside, Kumbakonam',
    phone: '+91 94433 99182',
    emergencyContact: '+91 98425 66710',
    emergencyContactRelation: 'Community Helper (Shanthi)',
    foodRequirement: 'Cooked Hot Meals & Warm Water',
    currentStockKg: 0.2,
    requiredStockKg: 2.5,
    stockUnit: 'kg',
    foodStatus: 'emergency',
    mealStatus: {
      breakfast: 'missed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 30.5,
    ambientHumidity: 61,
    coords: { lat: 10.9651, lng: 79.3882 },
    locationSharingActive: true,
    locationLastUpdated: '5 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Cannot cook due to acute dizziness, urgent meals needed',
    healthNotes: 'Fever, dizzy spell reported today morning',
    registeredDate: '18 Jan 2026',
    assistanceHistory: [
      {
        id: 'hist-8',
        date: '2026-09-23',
        type: 'SOS Meal Delivery',
        status: 'Out for Delivery',
        notes: 'Emergency alert dispatched to Volunteer Arun Kumar',
      },
    ],
  },
  {
    id: 'ben-008',
    code: 'CN-KUM-008',
    name: 'Subramanian',
    age: 83,
    gender: 'Male',
    area: 'Valangaiman',
    address: '11 Varadaraja Perumal Sannadhi, Valangaiman',
    phone: '+91 94439 12389',
    emergencyContact: '+91 94871 00293',
    emergencyContactRelation: 'Panchayat Volunteer (Ramesh)',
    foodRequirement: 'Rice, Sambar Dal, Mustard, Fenugreek',
    currentStockKg: 1.0,
    requiredStockKg: 2.5,
    stockUnit: 'kg',
    foodStatus: 'low',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 30.2,
    ambientHumidity: 60,
    coords: { lat: 10.8981, lng: 79.3892 },
    locationSharingActive: true,
    locationLastUpdated: '1 hour ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Requires easily digestible bland foods',
    healthNotes: 'Hearing difficulty, prefers SMS or loud voice',
    registeredDate: '22 Feb 2026',
    assistanceHistory: [],
  },
  {
    id: 'ben-009',
    code: 'CN-KUM-009',
    name: 'Janaki',
    age: 71,
    gender: 'Female',
    area: 'Darasuram',
    address: '15 Weaver Colony, Near Darasuram Railway Gate',
    phone: '+91 94428 55410',
    emergencyContact: '+91 93451 90123',
    emergencyContactRelation: 'Son (Sundar)',
    foodRequirement: 'Brown Rice, Chana Dal, Coconut',
    currentStockKg: 1.2,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'low',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'completed',
      dinner: 'pending',
    },
    ambientTemp: 29.3,
    ambientHumidity: 63,
    coords: { lat: 10.9601, lng: 79.3512 },
    locationSharingActive: true,
    locationLastUpdated: '20 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Pure vegetarian, needs weekly fresh greens',
    healthNotes: 'General weakness, manages independently',
    registeredDate: '01 Feb 2026',
    assistanceHistory: [
      {
        id: 'hist-9',
        date: '2026-09-23',
        type: 'Fresh Vegetable Basket',
        status: 'Delivered',
        notes: 'Delivered successfully at 10:21 AM',
      },
    ],
  },
  {
    id: 'ben-010',
    code: 'CN-KUM-010',
    name: 'Krishnan',
    age: 77,
    gender: 'Male',
    area: 'Koranattukaruppur',
    address: '22 Agraharam, Koranattukaruppur, Kumbakonam North',
    phone: '+91 94436 44819',
    emergencyContact: '+91 98420 11982',
    emergencyContactRelation: 'Friend (Nagarajan)',
    foodRequirement: 'Ponni Raw Rice, Groundnut Oil, Pepper',
    currentStockKg: 2.7,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'sufficient',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'completed',
      dinner: 'pending',
    },
    ambientTemp: 28.9,
    ambientHumidity: 64,
    coords: { lat: 10.9782, lng: 79.3791 },
    locationSharingActive: true,
    locationLastUpdated: '2 hours ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Traditional South Indian sattvic diet',
    healthNotes: 'Hypertension controlled by Siddha herbs',
    registeredDate: '11 Mar 2026',
    assistanceHistory: [],
  },
  {
    id: 'ben-011',
    code: 'CN-KUM-011',
    name: 'Valli',
    age: 73,
    gender: 'Female',
    area: 'Ullur',
    address: '6 Main Road, Ullur Village, Kumbakonam Rural',
    phone: '+91 94434 22019',
    emergencyContact: '+91 97880 33412',
    emergencyContactRelation: 'Daughter-in-law (Malar)',
    foodRequirement: 'Parboiled Rice, Black Gram, Turmeric',
    currentStockKg: 0.9,
    requiredStockKg: 2.5,
    stockUnit: 'kg',
    foodStatus: 'low',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 29.7,
    ambientHumidity: 62,
    coords: { lat: 10.9412, lng: 79.3985 },
    locationSharingActive: true,
    locationLastUpdated: '35 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Needs easily chewable items',
    healthNotes: 'Loss of back molars, requires soft diet',
    registeredDate: '19 Feb 2026',
    assistanceHistory: [],
  },
  {
    id: 'ben-012',
    code: 'CN-KUM-012',
    name: 'Narayanan',
    age: 80,
    gender: 'Male',
    area: 'Cholapuram',
    address: '3 Kothandaramaswamy Kovil Street, Cholapuram',
    phone: '+91 94421 88902',
    emergencyContact: '+91 94860 77110',
    emergencyContactRelation: 'Village Elder (Chandran)',
    foodRequirement: 'Fresh Cooked Meals, Warm Porridge',
    currentStockKg: 0.3,
    requiredStockKg: 2.5,
    stockUnit: 'kg',
    foodStatus: 'emergency',
    mealStatus: {
      breakfast: 'missed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 31.0,
    ambientHumidity: 58,
    coords: { lat: 11.0121, lng: 79.4124 },
    locationSharingActive: true,
    locationLastUpdated: '12 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Unable to light gas stove due to hand tremors',
    healthNotes: 'Parkinson symptoms, high fall risk',
    registeredDate: '09 Jan 2026',
    assistanceHistory: [
      {
        id: 'hist-10',
        date: '2026-09-23',
        type: 'Urgent Care Packet',
        status: 'Assigned',
        notes: 'Emergency alert raised for noon meal support',
      },
    ],
  },
  {
    id: 'ben-013',
    code: 'CN-KUM-013',
    name: 'Parvathi',
    age: 75,
    gender: 'Female',
    area: 'Kumbakonam Town',
    address: '51 Nageswaran South Street, Kumbakonam',
    phone: '+91 94438 00912',
    emergencyContact: '+91 98439 77810',
    emergencyContactRelation: 'Tenant (Sangeetha)',
    foodRequirement: 'Rice, Sambar Powder, Sesame Oil',
    currentStockKg: 0.4,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'critical',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 29.4,
    ambientHumidity: 63,
    coords: { lat: 10.9592, lng: 79.3781 },
    locationSharingActive: true,
    locationLastUpdated: '18 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Soft rice, tender dal',
    healthNotes: 'Lives alone on first floor with narrow staircase',
    registeredDate: '14 Feb 2026',
    assistanceHistory: [],
  },
  {
    id: 'ben-014',
    code: 'CN-KUM-014',
    name: 'Mani',
    age: 67,
    gender: 'Male',
    area: 'Swamimalai',
    address: '14 Bronze Foundry Lane, Swamimalai',
    phone: '+91 94429 66110',
    emergencyContact: '+91 93610 88291',
    emergencyContactRelation: 'Brother (Kandasamy)',
    foodRequirement: 'Steamed Rice, Green Vegetables, Curd',
    currentStockKg: 2.9,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'sufficient',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'completed',
      dinner: 'pending',
    },
    ambientTemp: 28.7,
    ambientHumidity: 65,
    coords: { lat: 10.9542, lng: 79.3245 },
    locationSharingActive: true,
    locationLastUpdated: '4 hours ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Normal traditional vegetarian',
    healthNotes: 'Recuperating from eye surgery',
    registeredDate: '26 Feb 2026',
    assistanceHistory: [],
  },
  {
    id: 'ben-015',
    code: 'CN-KUM-015',
    name: 'Radha',
    age: 78,
    gender: 'Female',
    area: 'Patteeswaram',
    address: '9 Thenupuriswarar West Street, Patteeswaram',
    phone: '+91 94432 99801',
    emergencyContact: '+91 97891 00214',
    emergencyContactRelation: 'Granddaughter (Pooja)',
    foodRequirement: 'Wheat Flour, Ragi, Raw Rice',
    currentStockKg: 1.0,
    requiredStockKg: 3.0,
    stockUnit: 'kg',
    foodStatus: 'low',
    mealStatus: {
      breakfast: 'completed',
      lunch: 'pending',
      dinner: 'pending',
    },
    ambientTemp: 30.0,
    ambientHumidity: 61,
    coords: { lat: 10.9215, lng: 79.3654 },
    locationSharingActive: true,
    locationLastUpdated: '50 mins ago',
    profilePhotoUrl: '',
    dietaryNotes: 'Wheat chapatis and millet porridge',
    healthNotes: 'Diabetic neuropathy in feet',
    registeredDate: '02 Mar 2026',
    assistanceHistory: [],
  },
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-001',
    code: 'CN-VOL-01',
    name: 'Arun Kumar',
    phone: '+91 98421 90123',
    serviceArea: 'Kumbakonam Town',
    availability: 'On Delivery',
    activeDeliveryId: 'del-101',
    completedDeliveries: 18,
    rating: 4.9,
    avatarUrl: '',
    currentCoords: { lat: 10.9638, lng: 79.3855 },
  },
  {
    id: 'vol-002',
    code: 'CN-VOL-02',
    name: 'Priya Sundaram',
    phone: '+91 97892 33410',
    serviceArea: 'Darasuram',
    availability: 'Available',
    completedDeliveries: 24,
    rating: 5.0,
    avatarUrl: '',
    currentCoords: { lat: 10.9590, lng: 79.3540 },
  },
  {
    id: 'vol-003',
    code: 'CN-VOL-03',
    name: 'Karthik Raja',
    phone: '+91 94430 88712',
    serviceArea: 'Swamimalai',
    availability: 'Available',
    completedDeliveries: 15,
    rating: 4.8,
    avatarUrl: '',
    currentCoords: { lat: 10.9555, lng: 79.3270 },
  },
  {
    id: 'vol-004',
    code: 'CN-VOL-04',
    name: 'Deepa Balan',
    phone: '+91 93601 22987',
    serviceArea: 'Patteeswaram',
    availability: 'On Delivery',
    activeDeliveryId: 'del-102',
    completedDeliveries: 12,
    rating: 4.9,
    avatarUrl: '',
    currentCoords: { lat: 10.9230, lng: 79.3635 },
  },
  {
    id: 'vol-005',
    code: 'CN-VOL-05',
    name: 'Saravanan V',
    phone: '+91 98433 11209',
    serviceArea: 'Thiruvidaimarudur',
    availability: 'Available',
    completedDeliveries: 21,
    rating: 4.9,
    avatarUrl: '',
    currentCoords: { lat: 10.9980, lng: 79.4570 },
  },
];

export const INITIAL_ASSISTANCE_REQUESTS: AssistanceRequest[] = [
  {
    id: 'req-201',
    beneficiaryId: 'ben-001',
    beneficiaryName: 'Lakshmi Devi',
    area: 'Kumbakonam Town',
    foodRequired: 'Ponni Rice (3kg) + Toor Dal (1kg)',
    quantity: '4 kg total ration kit',
    reason: 'Ration running out today, unable to walk to shop',
    priority: 'Urgent',
    status: 'Out for Delivery',
    requestedAt: '10:42 AM',
    assignedVolunteerId: 'vol-001',
    assignedVolunteerName: 'Arun Kumar',
    coords: { lat: 10.9625, lng: 79.3831 },
    deliveryNotes: 'Call daughter Revathi if door is latched from inside',
  },
  {
    id: 'req-202',
    beneficiaryId: 'ben-004',
    beneficiaryName: 'Gopal',
    area: 'Patteeswaram',
    foodRequired: 'Soft Rice & Nutrition Porridge Pouch',
    quantity: '3 days meal support',
    reason: 'Caregiver indisposed due to fever',
    priority: 'Urgent',
    status: 'Out for Delivery',
    requestedAt: '09:30 AM',
    assignedVolunteerId: 'vol-004',
    assignedVolunteerName: 'Deepa Balan',
    coords: { lat: 10.9241, lng: 79.3621 },
    deliveryNotes: 'Hand over to Venkatesh directly',
  },
  {
    id: 'req-203',
    beneficiaryId: 'ben-007',
    beneficiaryName: 'Kamala Devi',
    area: 'Kumbakonam Town',
    foodRequired: 'Emergency Hot Lunch & Electrolyte Kanji',
    quantity: 'Immediate meal packet',
    reason: 'Severe weakness and dizzy spell, missed morning meal',
    priority: 'Emergency',
    status: 'Assigned',
    requestedAt: '10:15 AM',
    assignedVolunteerId: 'vol-001',
    assignedVolunteerName: 'Arun Kumar',
    coords: { lat: 10.9651, lng: 79.3882 },
    deliveryNotes: 'Emergency SOS alert received, coordinate with neighbor Shanthi',
  },
  {
    id: 'req-204',
    beneficiaryId: 'ben-002',
    beneficiaryName: 'Ramasamy',
    area: 'Darasuram',
    foodRequired: 'Raw Rice (3kg) + Moong Dal (1kg)',
    quantity: '4 kg standard pack',
    reason: 'Stock critically below threshold (<0.8 kg)',
    priority: 'Urgent',
    status: 'Reviewed',
    requestedAt: '09:45 AM',
    coords: { lat: 10.9582, lng: 79.3564 },
    deliveryNotes: 'Volunteer assignment pending in Darasuram zone',
  },
  {
    id: 'req-205',
    beneficiaryId: 'ben-012',
    beneficiaryName: 'Narayanan',
    area: 'Cholapuram',
    foodRequired: 'Cooked Sambar Rice Box + Boiled Eggs',
    quantity: '2 meals',
    reason: 'Gas cylinder empty, unable to replace without assistance',
    priority: 'Emergency',
    status: 'Requested',
    requestedAt: '10:10 AM',
    coords: { lat: 11.0121, lng: 79.4124 },
    deliveryNotes: 'Village elder Chandran notified',
  },
];

export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: 'del-101',
    requestId: 'req-201',
    beneficiaryId: 'ben-001',
    beneficiaryName: 'Lakshmi Devi',
    beneficiaryPhone: '+91 94432 10871',
    volunteerId: 'vol-001',
    volunteerName: 'Arun Kumar',
    volunteerPhone: '+91 98421 90123',
    area: 'Kumbakonam Town',
    foodItems: 'Ponni Rice 3kg + Toor Dal 1kg',
    startCoords: { lat: 10.9602, lng: 79.3845 }, // CareNest Central Hub
    destCoords: { lat: 10.9625, lng: 79.3831 }, // Lakshmi Devi home
    currentVolunteerCoords: { lat: 10.9615, lng: 79.3838 },
    status: 'Out for Delivery',
    startedAt: '10:35 AM',
    distanceKm: 0.6,
    etaMinutes: 4,
  },
  {
    id: 'del-102',
    requestId: 'req-202',
    beneficiaryId: 'ben-004',
    beneficiaryName: 'Gopal',
    beneficiaryPhone: '+91 94862 11903',
    volunteerId: 'vol-004',
    volunteerName: 'Deepa Balan',
    volunteerPhone: '+91 93601 22987',
    area: 'Patteeswaram',
    foodItems: 'Elderly Nutrition Porridge Pouch + Soft Rice',
    startCoords: { lat: 10.9290, lng: 79.3660 },
    destCoords: { lat: 10.9241, lng: 79.3621 },
    currentVolunteerCoords: { lat: 10.9260, lng: 79.3640 },
    status: 'Out for Delivery',
    startedAt: '10:28 AM',
    distanceKm: 0.9,
    etaMinutes: 7,
  },
  {
    id: 'del-103',
    requestId: 'req-203',
    beneficiaryId: 'ben-007',
    beneficiaryName: 'Kamala Devi',
    beneficiaryPhone: '+91 94433 99182',
    volunteerId: 'vol-001',
    volunteerName: 'Arun Kumar',
    volunteerPhone: '+91 98421 90123',
    area: 'Kumbakonam Town',
    foodItems: 'Emergency Hot Lunch Kit',
    startCoords: { lat: 10.9602, lng: 79.3845 },
    destCoords: { lat: 10.9651, lng: 79.3882 },
    currentVolunteerCoords: { lat: 10.9602, lng: 79.3845 },
    status: 'Assigned',
    distanceKm: 1.2,
    etaMinutes: 12,
  },
  {
    id: 'del-104',
    requestId: 'req-206',
    beneficiaryId: 'ben-013',
    beneficiaryName: 'Parvathi',
    beneficiaryPhone: '+91 94438 00912',
    volunteerId: 'vol-002',
    volunteerName: 'Priya Sundaram',
    volunteerPhone: '+91 97892 33410',
    area: 'Kumbakonam Town',
    foodItems: 'Rice & Sambar Provisions (3kg)',
    startCoords: { lat: 10.9580, lng: 79.3650 },
    destCoords: { lat: 10.9592, lng: 79.3781 },
    currentVolunteerCoords: { lat: 10.9585, lng: 79.3710 },
    status: 'Accepted',
    distanceKm: 1.4,
    etaMinutes: 15,
  },
];

export const INITIAL_EMERGENCIES: EmergencyAlert[] = [
  {
    id: 'emg-001',
    beneficiaryId: 'ben-007',
    beneficiaryName: 'Kamala Devi',
    age: 79,
    area: 'Kumbakonam Town',
    phone: '+91 94433 99182',
    time: '10:15 AM',
    status: 'Volunteer Assigned',
    coords: { lat: 10.9651, lng: 79.3882 },
    notes: 'Elderly assistance button pressed. Dizziness, no morning meal taken. Volunteer Arun assigned.',
    assignedVolunteerId: 'vol-001',
    assignedVolunteerName: 'Arun Kumar',
  },
  {
    id: 'emg-002',
    beneficiaryId: 'ben-012',
    beneficiaryName: 'Narayanan',
    age: 80,
    area: 'Cholapuram',
    phone: '+91 94421 88902',
    time: '10:10 AM',
    status: 'Active',
    coords: { lat: 11.0121, lng: 79.4124 },
    notes: 'Urgent hunger alert. Tremors prevented cooking, food completely exhausted. Needs urgent dispatch.',
  },
];

export const INITIAL_MARKET_PRODUCTS: MarketProduct[] = [
  {
    id: 'prod-001',
    name: 'Traditional Meals (Full Thali)',
    description:
      'Authentic Kumbakonam vegetarian lunch served with Ponni boiled rice, arachivitta sambar, rasam, kootu, vegetable poriyal, mor (buttermilk), appalam, and signature payasam.',
    ingredients: ['Ponni Rice', 'Toor Dal', 'Drumstick', 'Pumpkin', 'Curd', 'Ghee', 'Spices'],
    price: 60,
    availableStock: 25,
    imageUrl: '/src/assets/images/market_traditional_meals_1790230565947.jpg',
    prepTime: 'Prepared Fresh at 11:00 AM daily',
    category: 'Traditional',
    isAvailable: true,
  },
  {
    id: 'prod-002',
    name: 'Rice & Curry Box',
    description:
      'Steamed hot rice with aromatic home-style spiced mixed vegetable curry, yellow moong dal tadka, and freshly grated coconut thuvaiyal.',
    ingredients: ['Steamed Rice', 'Yellow Dal', 'Brinjal', 'Tomato', 'Fresh Coconut', 'Mustard Seeds'],
    price: 70,
    availableStock: 18,
    imageUrl: '/src/assets/images/market_rice_curry_1790230577633.jpg',
    prepTime: 'Prepared Fresh at 11:30 AM',
    category: 'Traditional',
    isAvailable: true,
  },
  {
    id: 'prod-003',
    name: 'Healthy Millet Meal Box',
    description:
      'Nutritious diabetic-friendly lunch packed with steamed Little Millet (Samai), steamed greens (Keerai kootu), sprouted moong salad, and light cumin rasam.',
    ingredients: ['Samai Millet', 'Sirukeerai Greens', 'Sprouted Moong', 'Carrot', 'Cumin', 'Himalayan Salt'],
    price: 80,
    availableStock: 20,
    imageUrl: '/src/assets/images/market_healthy_meal_box_1790230590776.jpg',
    prepTime: 'Prepared Fresh at 11:15 AM',
    category: 'Healthy',
    isAvailable: true,
  },
  {
    id: 'prod-004',
    name: 'Breakfast Box (Idli & Vada Combo)',
    description:
      '4 soft melt-in-the-mouth steamed idlis and 1 crispy medu vada, served with traditional coconut chutney, onion-tomato kara chutney, and piping hot sambar.',
    ingredients: ['Idli Rice', 'Urad Dal', 'Fresh Coconut', 'Shallots', 'Asafoetida', 'Curry Leaves'],
    price: 50,
    availableStock: 30,
    imageUrl: '/src/assets/images/market_breakfast_box_1790230602279.jpg',
    prepTime: 'Hot & Ready from 7:00 AM',
    category: 'Breakfast',
    isAvailable: true,
  },
];

export const INITIAL_ORDERS: MarketOrder[] = [
  {
    id: 'ord-1042',
    orderNumber: 'CN-MKT-1042',
    customerName: 'Sundara Raman',
    customerPhone: '+91 98421 34912',
    deliveryAddress: '24 Town Railway Station Road, Kumbakonam',
    deliveryType: 'delivery',
    paymentMethod: 'UPI / GPay',
    items: [
      {
        productId: 'prod-003',
        productName: 'Healthy Millet Meal Box',
        price: 80,
        quantity: 2,
      },
      {
        productId: 'prod-004',
        productName: 'Breakfast Box (Idli & Vada Combo)',
        price: 50,
        quantity: 1,
      },
    ],
    totalAmount: 210,
    status: 'Preparing',
    createdAt: '10:25 AM',
    impactNote: 'Supports subsidizing 2 senior community meals today',
  },
  {
    id: 'ord-1041',
    orderNumber: 'CN-MKT-1041',
    customerName: 'Anitha Venkatesh',
    customerPhone: '+91 94432 88190',
    deliveryAddress: '15 Mahamaham West Street, Kumbakonam',
    deliveryType: 'pickup',
    paymentMethod: 'UPI / GPay',
    items: [
      {
        productId: 'prod-001',
        productName: 'Traditional Meals (Full Thali)',
        price: 60,
        quantity: 4,
      },
    ],
    totalAmount: 240,
    status: 'Ready',
    createdAt: '09:50 AM',
    impactNote: 'Supports subsidizing 2 senior community meals today',
  },
  {
    id: 'ord-1040',
    orderNumber: 'CN-MKT-1040',
    customerName: 'Dr. Subramaniam Clinic',
    customerPhone: '+91 94870 11234',
    deliveryAddress: 'Near Government Hospital, Kumbakonam',
    deliveryType: 'delivery',
    paymentMethod: 'UPI / GPay',
    items: [
      {
        productId: 'prod-001',
        productName: 'Traditional Meals (Full Thali)',
        price: 60,
        quantity: 10,
      },
      {
        productId: 'prod-002',
        productName: 'Rice & Curry Box',
        price: 70,
        quantity: 5,
      },
    ],
    totalAmount: 950,
    status: 'Delivered',
    createdAt: '08:45 AM',
    impactNote: 'Supports subsidizing 8 senior community meals today',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    type: 'request',
    message: 'Lakshmi Devi requested food (Ponni Rice & Toor Dal)',
    timestamp: '10:42 AM',
    severity: 'danger',
  },
  {
    id: 'act-2',
    type: 'location',
    message: 'Ramasamy updated GPS location sharing from Darasuram',
    timestamp: '10:39 AM',
    severity: 'info',
  },
  {
    id: 'act-3',
    type: 'delivery',
    message: 'Arun Kumar started delivery to Lakshmi Devi (ETA: 4 mins)',
    timestamp: '10:35 AM',
    severity: 'warning',
  },
  {
    id: 'act-4',
    type: 'food',
    message: "Saraswathi's food stock reached low threshold (1.1 kg remaining)",
    timestamp: '10:30 AM',
    severity: 'warning',
  },
  {
    id: 'act-5',
    type: 'market',
    message: '2 Healthy Meal Boxes ordered by Sundara Raman (#CN-MKT-1042)',
    timestamp: '10:25 AM',
    severity: 'success',
  },
  {
    id: 'act-6',
    type: 'delivery',
    message: "Janaki's vegetable delivery completed with photo proof verification",
    timestamp: '10:21 AM',
    severity: 'success',
  },
  {
    id: 'act-7',
    type: 'emergency',
    message: 'Emergency SOS alert received from Kamala Devi (79 yrs, Kumbakonam Town)',
    timestamp: '10:15 AM',
    severity: 'danger',
  },
];

export const INITIAL_FOOD_RECORDS: FoodRecord[] = [
  {
    id: 'frec-01',
    beneficiaryId: 'ben-001',
    beneficiaryName: 'Lakshmi Devi',
    area: 'Kumbakonam Town',
    foodType: 'Ponni Boiled Rice',
    quantity: 0.5,
    requiredQuantity: 3.0,
    unit: 'kg',
    temp: 29.2,
    humidity: 62,
    timestamp: '10:30 AM Today',
    photoUrl: '/src/assets/images/market_rice_curry_1790230577633.jpg',
    status: 'critical',
  },
  {
    id: 'frec-02',
    beneficiaryId: 'ben-002',
    beneficiaryName: 'Ramasamy',
    area: 'Darasuram',
    foodType: 'Raw Rice & Moong Dal',
    quantity: 0.8,
    requiredQuantity: 3.0,
    unit: 'kg',
    temp: 30.1,
    humidity: 59,
    timestamp: '09:40 AM Today',
    photoUrl: '/src/assets/images/market_rice_curry_1790230577633.jpg',
    status: 'critical',
  },
  {
    id: 'frec-03',
    beneficiaryId: 'ben-005',
    beneficiaryName: 'Saraswathi',
    area: 'Nachiyarkoil',
    foodType: 'Standard Rice Stock',
    quantity: 1.1,
    requiredQuantity: 3.0,
    unit: 'kg',
    temp: 29.5,
    humidity: 63,
    timestamp: '10:05 AM Today',
    photoUrl: '/src/assets/images/market_traditional_meals_1790230565947.jpg',
    status: 'low',
  },
  {
    id: 'frec-04',
    beneficiaryId: 'ben-003',
    beneficiaryName: 'Meenakshi',
    area: 'Swamimalai',
    foodType: 'Millet Provisions',
    quantity: 2.8,
    requiredQuantity: 3.0,
    unit: 'kg',
    temp: 28.6,
    humidity: 65,
    timestamp: '08:30 AM Today',
    photoUrl: '/src/assets/images/market_healthy_meal_box_1790230590776.jpg',
    status: 'sufficient',
  },
];
